// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomeCatIDK.PirateJim.Model;

#nullable disable

namespace SomeCatIDK.PirateJim.Migrations
{
    [DbContext(typeof(PirateJimDbContext))]
    [Migration("20250119153811_AutoMessageChannels")]
    partial class AutoMessageChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.GuildAttachmentChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("GuildAttachmentChannels");
                });

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.GuildRatingChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("GuildRatingChannels");
                });

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.GuildTimeoutChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("GuildTimeoutChannels");
                });

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.LastMessageChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("LastMessageChannels");
                });

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.UserTimeout", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId", "UserId");

                    b.ToTable("UserTimeouts");
                });
#pragma warning restore 612, 618
        }
    }
}
