// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomeCatIDK.PirateJim.Model;

#nullable disable

namespace SomeCatIDK.PirateJim.Migrations
{
    [DbContext(typeof(PirateJimDbContext))]
    partial class PirateJimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.GuildAttachmentChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("GuildAttachmentChannels");
                });

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.GuildRatingChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("GuildRatingChannels");
                });

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.GuildTimeoutChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("GuildTimeoutChannels");
                });

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.UserTimeout", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId", "UserId");

                    b.ToTable("UserTimeouts");
                });
            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.CachedMessage", b =>
                {
                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId");

                    b.ToTable("CachedMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
