// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomeCatIDK.PirateJim.Model;

#nullable disable

namespace SomeCatIDK.PirateJim.Migrations
{
    [DbContext(typeof(PirateJimDbContext))]
    partial class PirateJimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.GuildTimeoutChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("GuildTimeoutChannels");
                });

            modelBuilder.Entity("SomeCatIDK.PirateJim.Model.UserTimeout", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId", "UserId");

                    b.ToTable("UserTimeouts");
                });
#pragma warning restore 612, 618
        }
    }
}
